language: ruby
rvm:
  - 1.9.3
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get update
  - sudo apt-get install build-essential chrpath git-core libssl-dev libfontconfig1-dev
  - git clone git://github.com/ariya/phantomjs.git
  - cd phantomjs
  - git checkout 1.8
  - ./build.sh
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database gistflow_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - elasticsearch
notifications:
  email:
    - releu@me.com
    - makaroni4@gmail.com
